# Generated by Django 3.1.10 on 2021-05-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseNumber', models.IntegerField()),
                ('personName', models.CharField(max_length=200)),
                ('identityDocumentNumber', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
                ('dateOfOnesetOfSymptoms', models.DateField()),
                ('dateOfConfirmationOfInfectionByTesting', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
