# Generated by Django 3.1.10 on 2021-05-08 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CaseRecord', '0001_initial'),
        ('EventRecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaseRecord.caserecord')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventRecord.event')),
            ],
        ),
    ]
