# Generated by Django 3.1.10 on 2021-05-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueName', models.CharField(max_length=100)),
                ('venueLocation', models.CharField(max_length=100)),
                ('venueAddress', models.CharField(max_length=200)),
                ('xCoord', models.FloatField()),
                ('yCoord', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
